"""The launcher icons, and the jungle wiring that makes devices pick them up.

Two failure modes this guards against, both silent:

  * an icon regenerated by hand, or an edit to `make_icons.py` that was never
    re-run, so what is committed is not what the script produces (compared as
    pixels, not file bytes — PNG encoding is not reproducible across Pillow
    versions, which is how this test first failed in CI while passing locally);
  * a new size added to `SIZES` (or a new product added to the manifest) with
    no matching `resourcePath` line in `monkey.jungle`, so the device quietly
    falls back to the 40 px default and the compiler scales it.
"""
import pathlib
import re

import pytest

from conftest import REPO_ROOT
from make_icons import DEFAULT_SIZE, SIZES, stale, target_path

Image = pytest.importorskip("PIL.Image", reason="pillow renders the icons")

JUNGLE = REPO_ROOT / "monkey.jungle"

# device -> launcher icon size, from each device's compiler.json in the SDK.
# The SDK is not available in CI, so the mapping is pinned here; if you add a
# product to manifest.xml, add it here too and the jungle test will tell you
# whether it needs a resourcePath line.
DEVICE_ICON_SIZE = {
    "vivoactive4": 35,
    "vivoactive5": 56,
    "venu": 60,
    "epix2": 60,
    "fr265": 60,
    "fr965": 65,
    "venu2": 70,
    "venu3": 70,
    # Everything below takes the 40 px default in resources/.
    "fenix5plus": 40, "fenix6": 40, "fenix6pro": 40, "fenix7": 40, "fenix7pro": 40,
    "fenix8solar47mm": 40, "fr645m": 40, "fr745": 40, "fr945": 40, "fr955": 40,
    "marqathlete": 40,
    # Device definitions not installed locally (issue #1); all 240x240-class
    # watches, so the 40 px default is right for them.
    "enduro": 40, "fr165": 40, "fr245": 40, "fr245m": 40, "fr255": 40,
}


def jungle_text():
    return JUNGLE.read_text(encoding="utf-8")


def jungle_overrides():
    """{device: icon size} as monkey.jungle actually declares it."""
    pattern = re.compile(r"^(\w+)\.resourcePath\s*=.*resources-icon-(\d+)", re.M)
    return {m.group(1): int(m.group(2)) for m in pattern.finditer(jungle_text())}


def test_committed_icons_match_what_the_script_generates():
    assert stale() == [], "run `python tools/make_icons.py`"


def test_a_hand_edited_icon_is_reported_as_stale(tmp_path):
    # The test above only means something if stale() can actually fail.
    import shutil
    from make_icons import differs, target_path as tp

    src = REPO_ROOT / tp(DEFAULT_SIZE)
    copy = tmp_path / "launcher_icon.png"
    shutil.copy(src, copy)
    assert not differs(copy, DEFAULT_SIZE), "an untouched copy is not stale"

    with Image.open(copy) as img:
        edited = img.copy()
    edited.putpixel((DEFAULT_SIZE // 2, DEFAULT_SIZE // 2), (255, 0, 0, 255))
    edited.save(copy)

    assert differs(copy, DEFAULT_SIZE), "one changed pixel is enough"


@pytest.mark.parametrize("size", SIZES)
def test_each_icon_is_the_size_it_claims(size):
    path = REPO_ROOT / target_path(size)
    assert path.exists(), path
    with Image.open(path) as img:
        assert img.size == (size, size)
        assert img.mode == "RGBA", "the launcher composites the icon, so it needs alpha"


def test_the_unqualified_icon_is_the_default_size():
    # resources/ is the fallback for any device without a qualified folder, so
    # the size that lives there has to be the one most devices want.
    assert pathlib.PurePath(target_path(DEFAULT_SIZE)).parts == (
        "resources", "drawables", "launcher_icon.png")
    assert DEFAULT_SIZE in SIZES


def test_every_non_default_size_has_a_jungle_line():
    declared = set(jungle_overrides().values())
    expected = {s for s in SIZES if s != DEFAULT_SIZE}
    assert declared == expected, "a generated size no device points at is dead weight"


def test_every_device_needing_a_non_default_icon_has_one():
    overrides = jungle_overrides()
    for device, size in sorted(DEVICE_ICON_SIZE.items()):
        if size == DEFAULT_SIZE:
            assert device not in overrides, f"{device} takes the default; the override is redundant"
        else:
            assert overrides.get(device) == size, (
                f"{device} wants a {size}px icon; monkey.jungle says "
                f"{overrides.get(device)}"
            )


def test_every_jungle_override_points_at_a_folder_that_exists():
    for device, size in jungle_overrides().items():
        folder = REPO_ROOT / f"resources-icon-{size}"
        assert (folder / "drawables" / "launcher_icon.png").exists(), f"{device} -> {folder}"
        assert (folder / "drawables" / "drawables.xml").exists(), f"{device} -> {folder}"


def test_every_manifest_product_is_in_the_size_table():
    manifest = (REPO_ROOT / "manifest.xml").read_text(encoding="utf-8")
    products = set(re.findall(r'<iq:product id="([^"]+)"', manifest))
    missing = products - set(DEVICE_ICON_SIZE)
    assert not missing, (
        f"products with no known launcher icon size: {sorted(missing)}. "
        "Look it up in the SDK's Devices/<id>/compiler.json and add it here."
    )
