"""The vectors in the watch's tests still match the reference implementation.

AGENTS.md says `freelap_frame.py` and `FreelapProtocol`/`BroadcastFrame.mc`
must change in the same commit. That has always been a rule people were asked
to remember; this makes it a rule that fails.

`source-test/BroadcastFrameTest.mc` holds byte arrays generated by
`fake_chip.py --vectors`. If the Python encoder changes and the committed
vectors do not, the watch's tests keep passing against frames a chip would
never send -- the exact silent hole the rule exists to prevent. So the vectors
are re-derived here and compared byte for byte.

This is not a test of the decoder. It is a test that the two decoders are still
talking about the same thing.
"""
import re

import pytest

from conftest import REPO_ROOT
import fake_chip
import freelap_frame as ff

WATCH_TEST = REPO_ROOT / "source-test" / "BroadcastFrameTest.mc"


def monkeyc_bytes(name):
    """Pull a `const NAME = [0x..,..]b;` byte array out of the Monkey C test."""
    source = WATCH_TEST.read_text(encoding="utf-8")
    match = re.search(r"const\s+%s\s*=\s*\[(.*?)\]b\s*;" % name, source, flags=re.S)
    assert match, "%s is not in %s" % (name, WATCH_TEST.name)
    return bytes(int(b, 16) for b in re.findall(r"0x[0-9a-fA-F]{2}", match.group(1)))


# The generator call the vectors were produced from. Changing this without
# regenerating them is the mistake this file exists to catch.
COURSE = fake_chip.parse_course("S:0;L:30;L:60;F:100")


def test_the_watch_rep_vector_is_what_the_generator_still_produces():
    advertisement, scan_response = fake_chip.rep_frames(COURSE, speed_mps=10.0,
                                                        jitter=0.0)

    assert monkeyc_bytes("REP_AD") == advertisement
    assert monkeyc_bytes("REP_SR") == scan_response


def test_the_watch_wide_vector_is_what_the_builder_still_produces():
    # The frame whose counters are big enough for the two candidate masks to
    # disagree -- the case the vendor's worked example cannot reach (#6).
    assert monkeyc_bytes("WIDE_AD") == ff.build_advertisement(
        "ZZ", 1234, 7, 0x00FF0000, 0x00FF0000, 0x01FF0000)


def test_the_watch_vectors_decode_to_the_values_the_watch_asserts():
    advertisement = ff.decode_advertisement(monkeyc_bytes("REP_AD"))
    laps = ff.decode_scan_response(monkeyc_bytes("REP_SR"))

    # Every number here is also asserted in BroadcastFrameTest.mc. Duplicated
    # on purpose: the point is that both implementations agree, and a shared
    # constant would let them agree by construction rather than by decoding.
    assert advertisement.chip == "BC-9636"
    assert advertisement.lap_number == 0
    assert (advertisement.offset, advertisement.from_lap, advertisement.block) \
        == (3585, 3585, 13825)
    assert laps == [6657, 9729]
    assert ff.segments(advertisement, laps) == [3072, 3072, 4096]
    assert ff.cumulative(advertisement, laps) == [3072, 6144, 10240]
    assert ff.to_centiseconds(advertisement.split()) == 1000


def test_the_wide_vector_separates_the_two_masks_on_both_sides():
    advertisement = ff.decode_advertisement(monkeyc_bytes("WIDE_AD"))

    assert advertisement.chip == "ZZ-1234"
    assert advertisement.split(ff.MASK_NARROW) == 0
    assert advertisement.split(ff.MASK_WIDE) == 16777216


@pytest.mark.parametrize("name", ["REP_AD", "WIDE_AD"])
def test_every_advertisement_vector_is_a_valid_frame(name):
    assert ff.decode_advertisement(monkeyc_bytes(name)) is not None


def test_the_generated_header_warns_against_editing_by_hand():
    # A vector edited in place to make a failing test pass would defeat all of
    # the above, so the generator says not to.
    assert "Do not edit by hand" in fake_chip.monkeyc_vectors(
        fake_chip.synthetic_session(COURSE, 1))
