#!/usr/bin/env python3
"""Generate the launcher icon at every size the target devices ask for.

Garmin devices do not agree on launcher icon size — it ranges from 35 px
(vivoactive4) to 70 px (venu2, venu3) across the products in manifest.xml, and
it does **not** follow screen size: fr265, venu2 and epix2 are all 416x416 and
want 60, 70 and 60 px respectively. Supplying one 40x40 file makes the compiler
scale it for everything else, which is the blurry result you see in the
launcher.

So the icon is drawn, not hand-exported: one description here, rendered
crisply at each size, with the stroke weights scaled so it still reads at
35 px. Rerun after changing the artwork:

    python tools/make_icons.py            # writes resources-icon-<n>/
    python tools/make_icons.py --check    # non-zero if anything is stale

The mark is a stopwatch: a ring, a crown and a hand. Deliberately dull —
anything more detailed turns to mush at 35 px.
"""
import argparse
import io
import math
import os
import sys

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - guarded by the CLI
    Image = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Every launcher icon size the manifest's products ask for. Derived from the
# SDK's per-device compiler.json; regenerate the list with:
#   python -c "import json,os;D=r'<sdk devices>';..."
# The five products whose device definitions are not installed locally
# (enduro, fr165, fr245, fr245m, fr255) are all 240x240-class watches and take
# the 40 px icon, which is also the unqualified default in resources/.
SIZES = (35, 40, 56, 60, 65, 70)

# The size that lives in resources/ as the fallback for any device without a
# qualified folder.
DEFAULT_SIZE = 40

BACKGROUND = (0, 122, 194, 255)   # a blue that survives both light and dark UI
FOREGROUND = (255, 255, 255, 255)

# Supersample, then downscale: the SDK will not antialias for us, and a 35 px
# icon drawn directly looks like a staircase.
SUPERSAMPLE = 8


def draw_icon(size):
    """The launcher icon at `size` x `size`, as an RGBA Image."""
    if Image is None:
        raise SystemExit("pip install pillow")

    s = size * SUPERSAMPLE
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    c = s / 2.0
    # Leave a margin so the disc is not clipped by the launcher's own mask.
    r = s * 0.47
    d.ellipse([c - r, c - r, c + r, c + r], fill=BACKGROUND)

    # Stopwatch crown and bezel ring.
    ring = s * 0.055
    br = r * 0.72
    d.ellipse([c - br, c - br, c + br, c + br], outline=FOREGROUND, width=int(ring))

    crown_w = s * 0.16
    crown_h = s * 0.09
    d.rounded_rectangle(
        [c - crown_w / 2, c - br - ring - crown_h, c + crown_w / 2, c - br + ring * 0.2],
        radius=crown_h * 0.4, fill=FOREGROUND,
    )

    # A single hand, up and to the right. An earlier version used a chevron for
    # "runner crossing the line" and read as the numeral 7 at 35 px, which is
    # the whole reason these are rendered per size and eyeballed.
    arm = br * 0.66
    angle = math.radians(-52)
    tip = (c + arm * math.cos(angle), c + arm * math.sin(angle))
    d.line([(c, c), tip], fill=FOREGROUND, width=int(ring * 1.05))

    cap = ring * 0.525
    for point in ((c, c), tip):
        d.ellipse([point[0] - cap, point[1] - cap, point[0] + cap, point[1] + cap],
                  fill=FOREGROUND)

    return img.resize((size, size), Image.LANCZOS)


def png_bytes(size):
    buf = io.BytesIO()
    draw_icon(size).save(buf, format="PNG")
    return buf.getvalue()


def target_path(size):
    """Where the icon for `size` lives, relative to the repo root."""
    if size == DEFAULT_SIZE:
        return os.path.join("resources", "drawables", "launcher_icon.png")
    return os.path.join(f"resources-icon-{size}", "drawables", "launcher_icon.png")


def write_all(root=ROOT):
    """Write every icon and its drawables.xml. Returns the paths written."""
    written = []
    for size in SIZES:
        rel = target_path(size)
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as handle:
            handle.write(png_bytes(size))
        written.append(rel)

        if size != DEFAULT_SIZE:
            xml = os.path.join(os.path.dirname(path), "drawables.xml")
            with open(xml, "w", encoding="utf-8") as handle:
                handle.write(
                    "<drawables>\n"
                    f"    <!-- {size}x{size} launcher icon; generated by "
                    "tools/make_icons.py, do not edit. -->\n"
                    '    <bitmap id="LauncherIcon" filename="launcher_icon.png"/>\n'
                    "</drawables>\n"
                )
    return written


# How far a committed pixel may drift from a freshly rendered one before the
# icon counts as stale. Not zero: PNG encoding and LANCZOS resampling are not
# byte-identical across Pillow versions and platforms, so comparing file bytes
# fails in CI for a file that is visually identical. Two levels out of 255 is
# well below anything an eye or a hand edit would produce.
PIXEL_TOLERANCE = 2


def differs(path, size):
    """True if the icon at `path` is not what draw_icon(size) produces."""
    with Image.open(path) as committed:
        if committed.size != (size, size) or committed.mode != "RGBA":
            return True
        on_disk = committed.tobytes()
    fresh = draw_icon(size).tobytes()
    if len(on_disk) != len(fresh):
        return True
    for i in range(len(fresh)):
        if abs(on_disk[i] - fresh[i]) > PIXEL_TOLERANCE:
            return True
    return False


def stale(root=ROOT):
    """Icons on disk that do not match what this script would generate.

    Compared as pixels rather than as file bytes; see PIXEL_TOLERANCE.
    """
    out = []
    for size in SIZES:
        rel = target_path(size)
        path = os.path.join(root, rel)
        if not os.path.exists(path) or differs(path, size):
            out.append(rel)
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report stale icons instead of writing them")
    args = parser.parse_args(argv)

    if args.check:
        bad = stale()
        for path in bad:
            print(f"stale: {path}")
        print(f"{len(bad)} stale icon(s)")
        return 1 if bad else 0

    for path in write_all():
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
