#!/usr/bin/env python3
"""Chip scenarios: frames a real FxChip would send, and what the FIT must say.

The Connect IQ simulator cannot receive a Bluetooth frame without an nRF52
board, so the scenario suite enters the app one step later - at the decoder,
which is exactly where a scan result would hand the bytes over. Every module
from there to the FIT recorder takes its input as an argument (AGENTS.md,
"inject, don't fetch"), so the whole pipeline runs under `monkeydo` on real
watch code.

This file is the **oracle**. For each scenario it generates the frames with
`fake_chip` (itself checked against the vendor's worked example), decodes them
with `freelap_frame`, and works out the developer-field values the watch must
write - in the same exact integer arithmetic the watch uses, so that the two
agree byte for byte rather than approximately.

`--emit` writes `source-test/ScenarioVectors.mc`. It is generated, never
edited: `tools/tests/test_scenarios.py` regenerates it and fails if the
committed copy differs, the same guard `test_monkeyc_vectors.py` provides for
the decoder vectors.

Scenarios are chosen to cover what the vendor documents say varies:

  * the number of transmitters - two, the worked-example three, and the
    documented maximum of eleven;
  * the gap between them - down to the documented 10 m minimum;
  * the athlete's speed - a sprint and a walk, which is what moves the tick
    counts through very different ranges;
  * whose chip it is - a bound chip, and a stranger's that must write nothing;
  * a chip whose lap-number byte never increments (#80).
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fake_chip  # noqa: E402
import freelap_frame as ff  # noqa: E402

BOUND = ("BC", 9636)
STRANGER = ("ZZ", 1234)

# Chip ticks are 1/1024 s. Microseconds per tick is 1000000/1024 = 15625/16,
# which is exact only when the tick count is a multiple of 16; the residue is
# under a microsecond and is truncated, as docs/EXPORT.md records. The watch
# does this identical integer arithmetic in a Long, and the oracle must match
# it exactly - a float here would disagree with the watch on the last digit.
US_NUM, US_DEN = 15625, 16


def ticks_to_us(ticks):
    return (ticks * US_NUM) // US_DEN


def eleven_transmitters():
    return "S:0;" + ";".join("L:%d" % (20 * i) for i in range(1, 10)) + ";F:200"


# name -> (course spec, speed m/s, chip, reps, lap_number policy)
SCENARIOS = {
    "SPRINT30":  ("S:0;F:30",              8.0, BOUND,    1, None),
    "WORKED100": ("S:0;L:30;L:60;F:100",  10.0, BOUND,    1, None),
    "MAX11":     (eleven_transmitters(),   8.0, BOUND,    1, None),
    "MINGAP":    ("S:0;L:10;F:20",         6.0, BOUND,    1, None),
    "WALK60":    ("S:0;F:60",              2.0, BOUND,    1, None),
    "STRANGER":  ("S:0;L:30;L:60;F:100",   9.0, STRANGER, 1, None),
    "CONSTLAP":  ("S:0;L:30;L:60;F:100",  10.0, BOUND,    3, 0),
}


def frames_for(name):
    """[(advertisement, scan_response), ...] for a scenario, deterministic."""
    spec, speed, (prefix, chip_id), reps, lap_number = SCENARIOS[name]
    course = fake_chip.parse_course(spec)
    return fake_chip.synthetic_session(course, reps, speed_mps=speed, jitter=0.0,
                                       prefix=prefix, chip_id=chip_id,
                                       lap_number=lap_number)


def expected_for(name, advertisement, scan_response):
    """The FIT record values for one rep: per crossing, in order.

    Mirrors what the watch does: BroadcastRep.toCrossings() emits START at 0,
    then each crossing at its cumulative ticks converted to microseconds; the
    engine derives split = cum - previous cum, and distance from the course.
    """
    spec, _speed, _chip, _reps, _lap = SCENARIOS[name]
    course = fake_chip.parse_course(spec)
    adv = ff.decode_advertisement(advertisement)
    laps = ff.decode_scan_response(scan_response)
    cum_ticks = [0] + ff.cumulative(adv, laps)
    cum_us = [ticks_to_us(t) for t in cum_ticks]
    split_us = [0] + [cum_us[i] - cum_us[i - 1] for i in range(1, len(cum_us))]
    dist_m = [metres for _code, metres in course]
    assert len(dist_m) == len(cum_us), (name, len(dist_m), len(cum_us))
    return {"cum_us": cum_us, "split_us": split_us, "dist_m": dist_m}


def _bytes_literal(payload):
    return "[" + ",".join("0x%02x" % b for b in payload) + "]b"


def _numbers(values):
    return "[" + ",".join(str(int(v)) for v in values) + "]"


def _floats(values):
    return "[" + ",".join("%.1f" % v for v in values) + "]"


def emit():
    """The Monkey C constants the scenario suite asserts against."""
    lines = [
        "// Generated by `python tools/scenarios.py --emit`. Do not edit by hand:",
        "// tools/tests/test_scenarios.py regenerates this and fails if it differs.",
        "//",
        "// Frames a real FxChip would broadcast for each scenario, and the FIT",
        "// developer-field values the watch must write for them. The expected",
        "// values are computed by tools/scenarios.py in the same exact integer",
        "// arithmetic the watch uses, so agreement is byte for byte.",
        "",
    ]
    for name, (spec, speed, (prefix, chip_id), reps, lap_number) in SCENARIOS.items():
        lines.append("// %s: %s at %g m/s, chip %s-%04d%s" % (
            name, spec, speed, prefix, chip_id,
            "" if lap_number is None else ", lap number held at %d" % lap_number))
        # (:test) on every constant: source-test/ is compiled into every build
        # and only annotated symbols are dropped from a release, so without
        # this the vectors would ride along in the shipped .prg as dead
        # globals - against a 253-global cap on the 240 px products.
        lines.append('(:test) const SCN_%s_SPEC = "%s";' % (name, spec))
        for i, (ad, sr) in enumerate(frames_for(name)):
            suffix = "" if reps == 1 else "_%d" % i
            lines.append("(:test) const SCN_%s_AD%s = %s;" % (name, suffix, _bytes_literal(ad)))
            lines.append("(:test) const SCN_%s_SR%s = %s;" % (name, suffix, _bytes_literal(sr)))
            exp = expected_for(name, ad, sr)
            lines.append("(:test) const SCN_%s_CUM_US%s = %s;" % (name, suffix, _numbers(exp["cum_us"])))
            lines.append("(:test) const SCN_%s_SPLIT_US%s = %s;" % (name, suffix, _numbers(exp["split_us"])))
            lines.append("(:test) const SCN_%s_DIST_M%s = %s;" % (name, suffix, _floats(exp["dist_m"])))
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--emit", action="store_true",
                        help="write source-test/ScenarioVectors.mc")
    args = parser.parse_args(argv)
    text = emit()
    if args.emit:
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        out = os.path.join(root, "source-test", "ScenarioVectors.mc")
        with open(out, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("wrote %s" % out)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
