using Toybox.Lang;
using Toybox.Test;

// Issue #7: decode the real broadcast frame.
//
// The vectors below were generated by `tools/fake_chip.py --vectors`, not
// typed, because a vector transcribed by hand is one that can quietly disagree
// with the encoder it is meant to check.
//
// What makes them worth anything is the chain behind them. The vendor's worked
// example is confidential and cannot live in this repository, so it is checked
// against `tools/freelap_frame.py` on a machine that has the document; these
// vectors come out of that same verified implementation; and this file checks
// the watch against them. Every link is testable. Break the mirror between
// `freelap_frame.py` and `BroadcastFrame.mc` and the far end of the chain is
// gone while everything here still passes.
//
// Most of what follows is rejection, because at a track almost every frame the
// watch sees belongs to somebody's phone (#9) and Connect IQ has no scan
// filter to spare us them.

// One rep of S:0;L:30;L:60;F:100 at 10 m/s, chip BC-9636.
// Total 10.00 s, legs 3.00 / 3.00 / 4.00.
const REP_AD = [0x63,0x03,0x58,0x00,0x42,0x43,0xa4,0x25,0x01,0x0e,0x00,0x00,
                0x01,0x0e,0x00,0x00,0x01,0x36,0x00,0x00,0x00,0x0d,0xa1,0xd2,
                0x33,0x11]b;
const REP_SR = [0x63,0x03,0x01,0x1a,0x00,0x01,0x26,0x00,0x00,0x00,0x00,0x00,
                0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                0x00,0x00,0x00,0x00,0x00]b;

// A frame whose counters are big enough that the two candidate masks disagree.
const WIDE_AD = [0x63,0x03,0x58,0x07,0x5a,0x5a,0xd2,0x04,0x00,0x00,0xff,0x00,
                 0x00,0x00,0xff,0x00,0x00,0x00,0xff,0x01,0x00,0x0d,0xa1,0xd2,
                 0x33,0x11]b;

// ---------------------------------------------------------------------------
// The advertisement
// ---------------------------------------------------------------------------

(:test)
function testAnAdvertisementDecodesToTheChipAndItsCounters(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);

    Test.assertMessage(advertisement != null, "a Freelap frame decodes");
    Test.assertEqualMessage(advertisement.chip(), "BC-9636", "the id printed on the chip");
    Test.assertEqualMessage(advertisement.lapNumber, 0, "lap number");
    Test.assertEqualMessage(advertisement.offset, 3585l, "offset");
    Test.assertEqualMessage(advertisement.fromLap, 3585l, "from lap");
    Test.assertEqualMessage(advertisement.block, 13825l, "block");
    return true;
}

(:test)
function testTheDecodedChipMatchesWhatTheAthleteWouldType(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);

    // The whole of #64 rests on these two producing the same string: one from
    // the chip's bytes, the other from what the athlete typed into Garmin
    // Connect. If they ever disagree, a correctly bound watch ignores its own
    // chip and records nothing all session.
    Test.assertEqualMessage(advertisement.chip(), Settings.normaliseChipId("bc9636"),
                            "frame and setting agree");
    return true;
}

(:test)
function testAnAdvertisementAloneGivesTheRepTotal(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);

    // Deliberately without the scan response: whether the watch can read that
    // half at all is #60, and this is what still works if it cannot.
    var total = BroadcastFrame.toCentiseconds(
        advertisement.split(BroadcastFrame.MASK_WIDE), :round);

    Test.assertEqualMessage(total, 1000, "10.00 s");
    Test.assertEqualMessage(BroadcastFrame.formatTime(total), "00:10.00", "rendered");
    return true;
}

// ---------------------------------------------------------------------------
// The scan response
// ---------------------------------------------------------------------------

(:test)
function testTheScanResponseGivesTheIntermediateCrossings(logger as Test.Logger) as Lang.Boolean {
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    TestSupport.assertArrayEquals(laps, [6657, 9729], "two intermediates");
    return true;
}

(:test)
function testTrailingZeroesAreAbsentLapsNotCrossingsAtZero(logger as Test.Logger) as Lang.Boolean {
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    // The payload is a fixed 27 bytes whatever the course, so nine slots are
    // always there. Reading them all would invent seven crossings at the
    // chip's epoch and turn a 3-leg rep into a 10-leg one.
    Test.assertEqualMessage(laps.size(), 2, "not nine");
    return true;
}

(:test)
function testACourseWithNoIntermediatesDecodesToNoLaps(logger as Test.Logger) as Lang.Boolean {
    var empty = [0x63,0x03,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                 0x00,0x00,0x00,0x00,0x00]b;

    var laps = BroadcastFrame.decodeScanResponse(empty);

    // A start and a finish is a perfectly good course, so this is not an error.
    Test.assertMessage(laps != null, "decoded");
    Test.assertEqualMessage(laps.size(), 0, "no intermediates");
    return true;
}

// ---------------------------------------------------------------------------
// Arithmetic
// ---------------------------------------------------------------------------

(:test)
function testEveryLegOfTheRepIsRecovered(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    var legs = BroadcastFrame.segments(advertisement, laps, BroadcastFrame.MASK_WIDE);

    TestSupport.assertArrayEquals(legs, [3072, 3072, 4096], "ticks per leg");
    return true;
}

(:test)
function testTheFinalLegComesFromTheAdvertisementNotTheScanResponse(
        logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    var legs = BroadcastFrame.segments(advertisement, laps, BroadcastFrame.MASK_WIDE);

    // Two intermediates but three legs. The finish is not a crossing in the
    // scan response, and forgetting that loses the last leg of every rep -
    // which looks like a misconfigured course, not a decoding bug.
    Test.assertEqualMessage(legs.size(), laps.size() + 1, "one more leg than crossings");
    Test.assertEqualMessage(legs[2], 4096, "the run-in to the finish");
    return true;
}

(:test)
function testTheLegsOfARepAddUpToTheRep(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    var legs = BroadcastFrame.segments(advertisement, laps, BroadcastFrame.MASK_WIDE);
    var total = 0;
    for (var i = 0; i < legs.size(); i++) { total += legs[i]; }

    // The cheapest possible check that a frame was read correctly, and one the
    // vendor document never states: if any offset were wrong this would not
    // hold.
    Test.assertEqualMessage(total, advertisement.split(BroadcastFrame.MASK_WIDE),
                            "legs sum to the rep");
    return true;
}

(:test)
function testCumulativeTimesRunFromTheStart(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);

    var splits = BroadcastFrame.cumulative(advertisement, laps, BroadcastFrame.MASK_WIDE);

    TestSupport.assertArrayEquals(splits, [3072, 6144, 10240], "cumulative ticks");
    return true;
}

(:test)
function testTheLegsConvertToTheTimesTheAthleteRan(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(REP_AD);
    var laps = BroadcastFrame.decodeScanResponse(REP_SR);
    var legs = BroadcastFrame.segments(advertisement, laps, BroadcastFrame.MASK_WIDE);

    // 30 m, 30 m and 40 m at 10 m/s.
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(legs[0], :round), 300, "3.00 s");
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(legs[1], :round), 300, "3.00 s");
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(legs[2], :round), 400, "4.00 s");
    return true;
}

(:test)
function testTruncationAndRoundingDifferWhereTheAuthoritiesDo(
        logger as Test.Logger) as Lang.Boolean {
    // 2057 ticks is the leg that reads 02.00 in the vendor document's worked
    // example and 02.01 in the MyFreelap screenshot beside it. The app rounds,
    // because #25 measures us against MyFreelap.
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(2057, :truncate), 200, "document");
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(2057, :round), 201, "MyFreelap");

    // And they agree everywhere that is not near a boundary, which is why the
    // disagreement shows up exactly once in that example.
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(2646, :truncate), 258, "agree");
    Test.assertEqualMessage(BroadcastFrame.toCentiseconds(2646, :round), 258, "agree");
    return true;
}

(:test)
function testTimesRenderTheWayMyFreelapShowsThem(logger as Test.Logger) as Lang.Boolean {
    Test.assertEqualMessage(BroadcastFrame.formatTime(1050), "00:10.50", "ten and a half");
    Test.assertEqualMessage(BroadcastFrame.formatTime(258), "00:02.58", "under ten");
    Test.assertEqualMessage(BroadcastFrame.formatTime(0), "00:00.00", "zero");
    Test.assertEqualMessage(BroadcastFrame.formatTime(6000), "01:00.00", "a minute");
    Test.assertEqualMessage(BroadcastFrame.formatTime(5999), "00:59.99", "just under");
    return true;
}

// ---------------------------------------------------------------------------
// 32-bit counters, and the mask that is still open
// ---------------------------------------------------------------------------

(:test)
function testACounterWithItsTopBitSetDoesNotComeBackNegative(
        logger as Test.Logger) as Lang.Boolean {
    // A Monkey C Number is signed, so a chip that has been running long enough
    // to set the top bit would decode to a negative block and a negative rep
    // time. The fields are Longs for exactly this reason, and a watch is the
    // only place it shows up - the Python reference has arbitrary precision
    // and would never notice.
    var high = [0x63,0x03,0x58,0x00,0x42,0x43,0xa4,0x25,0x00,0x00,0x00,0x00,
                0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0x00,0x0d,0xa1,0xd2,
                0x33,0x11]b;

    var advertisement = BroadcastFrame.decodeAdvertisement(high);

    Test.assertMessage(advertisement.block > 0, "block is positive");
    Test.assertMessage(advertisement.split(BroadcastFrame.MASK_WIDE) > 0,
                       "and so is the rep time");
    return true;
}

(:test)
function testTheTwoCandidateMasksDisagreeOnAWideFrame(logger as Test.Logger) as Lang.Boolean {
    var advertisement = BroadcastFrame.decodeAdvertisement(WIDE_AD);

    // This is the case the vendor's worked example cannot reach, and it is why
    // the mask is still a parameter rather than a constant (#6). If these ever
    // compare equal, the ambiguity has stopped mattering and #6 should be
    // reread rather than this test relaxed.
    Test.assertEqualMessage(advertisement.split(BroadcastFrame.MASK_NARROW), 0, "narrow");
    Test.assertEqualMessage(advertisement.split(BroadcastFrame.MASK_WIDE), 16777216, "wide");
    return true;
}

// ---------------------------------------------------------------------------
// Rejection: everything else the watch will hear at a track
// ---------------------------------------------------------------------------

(:test)
function testAnotherManufacturersBeaconIsIgnored(logger as Test.Logger) as Lang.Boolean {
    var apple = [0x4c,0x00,0x02,0x15,0xaa,0xbb,0xcc,0xdd,0x00,0x00,0x00,0x00,
                 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                 0x00,0x00]b;

    Test.assertMessage(BroadcastFrame.decodeAdvertisement(apple) == null,
                       "an iBeacon is not a lap");
    return true;
}

(:test)
function testAFreelapFrameOfAnotherTypeIsIgnored(logger as Test.Logger) as Lang.Boolean {
    var other = REP_AD.slice(0, null);
    other[2] = 0x59;   // not 'X'

    // Freelap sell more than one product under this company identifier, so
    // matching the company alone is not enough.
    Test.assertMessage(BroadcastFrame.decodeAdvertisement(other) == null, "wrong frame type");
    return true;
}

(:test)
function testATruncatedAdvertisementIsRejectedRatherThanMisread(
        logger as Test.Logger) as Lang.Boolean {
    // Decoding a short frame would read past the end, or worse, read fields
    // that happen to be there and produce a plausible wrong time.
    Test.assertMessage(BroadcastFrame.decodeAdvertisement(REP_AD.slice(0, 10)) == null, "10");
    Test.assertMessage(BroadcastFrame.decodeAdvertisement(REP_AD.slice(0, 23)) == null, "23");
    Test.assertMessage(BroadcastFrame.decodeAdvertisement([]b) == null, "empty");
    return true;
}

(:test)
function testNothingAtAllIsRejected(logger as Test.Logger) as Lang.Boolean {
    Test.assertMessage(BroadcastFrame.decodeAdvertisement(null) == null, "null");
    Test.assertMessage(BroadcastFrame.decodeScanResponse(null) == null, "null");
    Test.assertMessage(BroadcastFrame.decodeAdvertisement("not bytes") == null, "wrong type");
    return true;
}

(:test)
function testANonAsciiChipPrefixIsRejected(logger as Test.Logger) as Lang.Boolean {
    var broken = REP_AD.slice(0, null);
    broken[4] = 0xff;

    // A prefix that is not text means this is not the frame we think it is,
    // and rendering it would put mojibake where the athlete expects their
    // chip id.
    Test.assertMessage(BroadcastFrame.decodeAdvertisement(broken) == null, "not text");
    return true;
}

// ---------------------------------------------------------------------------
// The shape Connect IQ hands us, which is not documented (#60)
// ---------------------------------------------------------------------------

(:test)
function testAPayloadWithoutTheCompanyIdentifierStillDecodes(
        logger as Test.Logger) as Lang.Boolean {
    var body = REP_AD.slice(2, null);

    // getManufacturerSpecificData() may or may not include the two bytes it
    // matched on; the SDK does not say. Being two bytes out on every field
    // would decode to plausible nonsense rather than to an error, so both
    // shapes are accepted.
    var advertisement = BroadcastFrame.decodeAdvertisement(body);

    Test.assertMessage(advertisement != null, "decoded without the identifier");
    Test.assertEqualMessage(advertisement.chip(), "BC-9636", "same chip");
    Test.assertEqualMessage(advertisement.block, 13825l, "same counters");
    return true;
}

(:test)
function testAScanResponseWithoutTheCompanyIdentifierStillDecodes(
        logger as Test.Logger) as Lang.Boolean {
    var laps = BroadcastFrame.decodeScanResponse(REP_SR.slice(2, null));

    TestSupport.assertArrayEquals(laps, [6657, 9729], "same crossings");
    return true;
}

// ---------------------------------------------------------------------------
// Repeats
// ---------------------------------------------------------------------------

(:test)
function testDecodingTheSameFrameTwiceGivesTheSameAnswer(logger as Test.Logger) as Lang.Boolean {
    // A chip repeats its frame throughout the advertising window, so this is
    // the normal case rather than an edge one. The decoder holds no state, and
    // deciding that two frames are one rep is the caller's job (#9).
    var first = BroadcastFrame.decodeAdvertisement(REP_AD);
    var second = BroadcastFrame.decodeAdvertisement(REP_AD);

    Test.assertEqualMessage(first.chip(), second.chip(), "same chip");
    Test.assertEqualMessage(first.block, second.block, "same counters");
    Test.assertEqualMessage(first.lapNumber, second.lapNumber, "same lap number");
    return true;
}

(:test)
function testTwoChipsDecodeIndependently(logger as Test.Logger) as Lang.Boolean {
    var mine = BroadcastFrame.decodeAdvertisement(REP_AD);
    var theirs = BroadcastFrame.decodeAdvertisement(WIDE_AD);

    // Under broadcast the watch hears every chip on the track whether it wants
    // to or not, so telling them apart is the whole of #63.
    Test.assertEqualMessage(mine.chip(), "BC-9636", "mine");
    Test.assertEqualMessage(theirs.chip(), "ZZ-1234", "somebody else's");
    Test.assertEqualMessage(theirs.lapNumber, 7, "on their seventh rep");
    return true;
}
