using Toybox.Lang;
using Toybox.Test;

// Chip scenarios, end to end on the watch's own code.
//
// Each test feeds frames a real FxChip would broadcast - generated by
// tools/scenarios.py from the vendor's frame layout - into the app at the
// point where a scan result would hand them over, and follows them through
// the decoder, the rep tracker, the split engine and the FIT recorder. What
// comes out the far end is the developer-field values that would be in the
// activity file, captured by FakeSession.
//
// The expected values come from the same oracle that generated the frames,
// computed in the same exact integer arithmetic the watch uses, so agreement
// is byte for byte. If the oracle and the watch ever disagree, one of them is
// wrong and this is where it shows. If they agree with each other but not
// with a chip, that is what the confidential fixture behind freelap_frame.py
// and the hardware runs in docs/TESTING.md are for.
//
// ScenarioVectors.mc is generated; tools/tests/test_scenarios.py fails if it
// is stale.

const SCN_BOUND = "BC-9636";

// Decode, track, adapt, feed the engine, drain the recorder. Returns the rep
// the tracker produced, or null - a scenario about a stranger's chip expects
// null and asserts on what was NOT written.
//
// Rigs are built with clearAfterWrite off. With it on, the recorder follows
// each rep's records with one blanking record so the split fields do not
// linger on every later 1 Hz record - a real feature, tested in
// FitRecordFieldsTest, and one that would put a trailing zero on every value
// array asserted here. These tests are about the values.
(:test)
module ScenarioRig {
    function play(rig, tracker as RepTracker, advertisement as Lang.ByteArray,
                  scanResponse as Lang.ByteArray) as BroadcastRep? {
        var adv = BroadcastFrame.decodeAdvertisement(advertisement);
        var laps = BroadcastFrame.decodeScanResponse(scanResponse);
        var rep = tracker.onFrame(adv, laps);
        if (rep != null) {
            rig.engine.onRepBurst(rep.toCrossings(), 1000);
            // Drain until idle rather than counting ticks: the recorder spends
            // one tick per record and then one more to cut the lap, and a rig
            // that hard-codes that cadence breaks the moment it changes.
            TestSupport.tickUntilIdle(rig.recorder, 64);
        }
        return rep;
    }

    function assertFit(session, name as Lang.String, cumUs as Lang.Array,
                       splitUs as Lang.Array, distM as Lang.Array) as Void {
        TestSupport.assertArrayEquals(session.valuesOf("fl_cum_us"), cumUs, name + " fl_cum_us");
        TestSupport.assertArrayEquals(session.valuesOf("fl_split_us"), splitUs, name + " fl_split_us");
        TestSupport.assertArrayEquals(session.valuesOf("fl_dist_m"), distM, name + " fl_dist_m");
    }
}

// ---------------------------------------------------------------------------
// Distances and transmitter counts
// ---------------------------------------------------------------------------

(:test)
function testASprintBetweenTwoTransmittersReachesTheFit(logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_SPRINT30_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    var rep = ScenarioRig.play(rig, tracker, SCN_SPRINT30_AD, SCN_SPRINT30_SR);

    // Start and finish only: no scan-response laps at all. This is also the
    // whole product if #60 is answered no, so it has to work on its own.
    Test.assertMessage(rep != null, "a rep");
    Test.assertEqualMessage(rep.segments.size(), 1, "one leg");
    ScenarioRig.assertFit(session, "SPRINT30", SCN_SPRINT30_CUM_US, SCN_SPRINT30_SPLIT_US,
                          SCN_SPRINT30_DIST_M);
    Test.assertEqualMessage(session.countOf("addLap"), 1, "one Garmin lap for one rep");
    return true;
}

(:test)
function testTheWorkedExampleShapeReachesTheFit(logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_WORKED100_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_WORKED100_AD, SCN_WORKED100_SR);

    ScenarioRig.assertFit(session, "WORKED100", SCN_WORKED100_CUM_US, SCN_WORKED100_SPLIT_US,
                          SCN_WORKED100_DIST_M);
    TestSupport.assertArrayEquals(session.valuesOf("fl_tx_idx"), [0, 1, 2, 3],
                                  "every crossing matched to its transmitter, in order");
    TestSupport.assertArrayEquals(session.valuesOf("fl_tx_code"),
                                  [TxCode.START, TxCode.LAP, TxCode.LAP, TxCode.FINISH],
                                  "ordinal codes: first is START, last is FINISH");
    return true;
}

(:test)
function testTheDocumentedMaximumOfElevenTransmittersReachesTheFit(
        logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_MAX11_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    var rep = ScenarioRig.play(rig, tracker, SCN_MAX11_AD, SCN_MAX11_SR);

    // Nine intermediates in the scan response, ten legs, eleven records. The
    // vendor's "10 intermediate times" and the frame's nine slots agree here.
    Test.assertEqualMessage(rep.segments.size(), 10, "ten legs");
    Test.assertEqualMessage(session.field("fl_split_us").writes(), 11, "eleven records");
    ScenarioRig.assertFit(session, "MAX11", SCN_MAX11_CUM_US, SCN_MAX11_SPLIT_US, SCN_MAX11_DIST_M);
    return true;
}

(:test)
function testTransmittersAtTheMinimumGapReachTheFit(logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_MINGAP_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_MINGAP_AD, SCN_MINGAP_SR);

    // 10 m is the documented minimum, not below it, so this is a legal course
    // and Course must not have warned about it.
    Test.assertEqualMessage(rig.engine.course.problem(), "", "a legal course");
    ScenarioRig.assertFit(session, "MINGAP", SCN_MINGAP_CUM_US, SCN_MINGAP_SPLIT_US,
                          SCN_MINGAP_DIST_M);
    return true;
}

// ---------------------------------------------------------------------------
// Speed
// ---------------------------------------------------------------------------

(:test)
function testAWalkingRepWithLargeTickCountsReachesTheFitExactly(
        logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_WALK60_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_WALK60_AD, SCN_WALK60_SR);

    // 30 s is 30 720 ticks: the tick-to-microsecond conversion has to be done
    // in a Long and truncated identically to the oracle, or the last digits
    // disagree here.
    ScenarioRig.assertFit(session, "WALK60", SCN_WALK60_CUM_US, SCN_WALK60_SPLIT_US,
                          SCN_WALK60_DIST_M);
    Test.assertEqualMessage(session.valuesOf("fl_cum_us")[1], 30000000, "exactly 30 s");
    return true;
}

// ---------------------------------------------------------------------------
// Whose chip
// ---------------------------------------------------------------------------

(:test)
function testAStrangersRepWritesNothingToTheFit(logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_STRANGER_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    var rep = ScenarioRig.play(rig, tracker, SCN_STRANGER_AD, SCN_STRANGER_SR);

    // ZZ-1234 ran a perfectly good rep on the same course. It is not ours,
    // and not one byte of it may reach our activity file.
    Test.assertMessage(rep == null, "not our chip");
    Test.assertEqualMessage(session.field("fl_split_us").writes(), 0, "no records");
    Test.assertEqualMessage(session.countOf("addLap"), 0, "no lap");
    return true;
}

(:test)
function testAStrangerBetweenTwoOfOurRepsChangesNothing(logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_WORKED100_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_0, SCN_CONSTLAP_SR_0);
    ScenarioRig.play(rig, tracker, SCN_STRANGER_AD, SCN_STRANGER_SR);
    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_1, SCN_CONSTLAP_SR_1);

    Test.assertEqualMessage(session.countOf("addLap"), 2, "two laps, both ours");
    Test.assertEqualMessage(tracker.repsSeen, 2, "two reps");
    TestSupport.assertArrayEquals(session.valuesOf("fl_rep"), [1, 1, 1, 1, 2, 2, 2, 2],
                                  "rep numbers unbroken by the stranger");
    return true;
}

// ---------------------------------------------------------------------------
// A chip that never increments its lap number (#80)
// ---------------------------------------------------------------------------

(:test)
function testThreeRepsWithAConstantLapNumberAreThreeLapsInTheFit(
        logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_CONSTLAP_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_0, SCN_CONSTLAP_SR_0);
    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_1, SCN_CONSTLAP_SR_1);
    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_2, SCN_CONSTLAP_SR_2);

    // Keyed on the lap-number byte this would be one rep and one lap. Keyed
    // on the finish it is three, which is what the athlete ran.
    Test.assertEqualMessage(session.countOf("addLap"), 3, "three Garmin laps");
    Test.assertEqualMessage(session.field("fl_split_us").writes(), 12, "three reps of four records");
    Test.assertEqualMessage(session.lapValue(2, "fl_rep"), 3, "the third lap is rep 3");
    return true;
}

(:test)
function testEachRepOfTheConstantLapSessionCarriesItsOwnTimes(
        logger as Test.Logger) as Lang.Boolean {
    var session = new FakeSession();
    var rig = TestSupport.recorderOnWith(session, SCN_CONSTLAP_SPEC, false);
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);

    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_0, SCN_CONSTLAP_SR_0);
    ScenarioRig.play(rig, tracker, SCN_CONSTLAP_AD_1, SCN_CONSTLAP_SR_1);

    // Rep 2 must be written from its own frame, not as a copy of rep 1: its
    // cumulative times restart at zero and its splits are its own.
    var cum = session.valuesOf("fl_cum_us");
    TestSupport.assertArrayEquals(cum.slice(0, 4), SCN_CONSTLAP_CUM_US_0, "rep 1 times");
    TestSupport.assertArrayEquals(cum.slice(4, 8), SCN_CONSTLAP_CUM_US_1, "rep 2 times");
    return true;
}

// ---------------------------------------------------------------------------
// The adapter itself
// ---------------------------------------------------------------------------

(:test)
function testCrossingsStartAtZeroAndEndAtTheRepTotal(logger as Test.Logger) as Lang.Boolean {
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);
    var rep = tracker.onFrame(BroadcastFrame.decodeAdvertisement(SCN_WORKED100_AD),
                              BroadcastFrame.decodeScanResponse(SCN_WORKED100_SR));

    var crossings = rep.toCrossings();

    Test.assertEqualMessage(crossings.size(), 4, "start, two intermediates, finish");
    Test.assertEqualMessage(crossings[0].timeUs, 0l, "the start is the origin");
    Test.assertEqualMessage(crossings[0].code, TxCode.START, "first is START");
    Test.assertEqualMessage(crossings[1].code, TxCode.LAP, "middle is LAP");
    Test.assertEqualMessage(crossings[3].code, TxCode.FINISH, "last is FINISH");
    Test.assertEqualMessage(crossings[3].chipId, SCN_BOUND, "and it says whose");
    return true;
}

(:test)
function testARepWithNoIntermediatesIsStartThenFinish(logger as Test.Logger) as Lang.Boolean {
    var tracker = new RepTracker(SCN_BOUND, BroadcastFrame.MASK_WIDE);
    var rep = tracker.onFrame(BroadcastFrame.decodeAdvertisement(SCN_SPRINT30_AD),
                              BroadcastFrame.decodeScanResponse(SCN_SPRINT30_SR));

    var crossings = rep.toCrossings();

    // Two crossings, no LAP between them. An adapter that emitted a LAP for a
    // one-leg rep would mismatch every two-transmitter course.
    Test.assertEqualMessage(crossings.size(), 2, "two crossings");
    Test.assertEqualMessage(crossings[1].code, TxCode.FINISH, "second is FINISH");
    return true;
}
